// SPDX-License-Identifier: Apache-2.0

package wire

// Drawing annotation wire DTOs (M14-F02 #813): the centre-of-gravity marker (a CoG indicator on
// a view, positioned from the referenced model's mass properties) and revision clouds (scalloped
// markup over a sheet region). Both are sheet-level annotations whose 2D geometry is generated by
// the host (/source, model/drawing).

// DrawingAnnotationInfo is the JSON shape of one drawing annotation.
type DrawingAnnotationInfo struct {
	Name       string `json:"name"`
	Kind       string `json:"kind"`               // types.DrawingAnnotationKind ("cog"/"revisionCloud"/"centerMark"/"centerline"/"featureControlFrame")
	ViewName   string `json:"viewName,omitempty"` // the view a CoG marker / centre mark is on
	Tag        string `json:"tag,omitempty"`      // a revision cloud's label
	CurveCount int    `json:"curveCount"`
}

// ListDrawingAnnotationsResult is the response of [MethodDrawingAnnotationsList].
type ListDrawingAnnotationsResult struct {
	Annotations []DrawingAnnotationInfo `json:"annotations"`
}

// AddCoGMarkerArgs is the request of [MethodDrawingAnnotationsAddCoG]: a centre-of-gravity marker
// on ViewName, positioned at the referenced model's centre of mass projected into that view.
type AddCoGMarkerArgs struct {
	Name     string `json:"name,omitempty"`
	ViewName string `json:"viewName"`
}

// AddRevisionCloudArgs is the request of [MethodDrawingAnnotationsAddRevisionCloud]: a scalloped
// cloud over the sheet rectangle (XMM, YMM, WidthMM, HeightMM), with an optional revision Tag.
type AddRevisionCloudArgs struct {
	Name     string  `json:"name,omitempty"`
	XMM      float64 `json:"xmm"`
	YMM      float64 `json:"ymm"`
	WidthMM  float64 `json:"widthMm"`
	HeightMM float64 `json:"heightMm"`
	Tag      string  `json:"tag,omitempty"`
}

// AddCenterMarksArgs is the request of [MethodDrawingAnnotationsAddCenterMarks]: a centre mark
// (crosshair) at the centre of every circular model edge in ViewName. Each mark attaches to its
// edge, so it re-projects when the model changes. Coincident projections are marked once.
type AddCenterMarksArgs struct {
	ViewName string `json:"viewName"`
}

// CenterMarksResult is the response of [MethodDrawingAnnotationsAddCenterMarks]: the marks created.
type CenterMarksResult struct {
	Annotations []DrawingAnnotationInfo `json:"annotations"`
}

// AddCenterlinesArgs is the request of [MethodDrawingAnnotationsAddCenterlines]: the horizontal and
// vertical dash-dot symmetry centerlines through ViewName's centre, spanning its extent. The lines
// re-derive from the view's bounds, so they track the model.
type AddCenterlinesArgs struct {
	Name     string `json:"name,omitempty"`
	ViewName string `json:"viewName"`
}

// AddFeatureControlFrameArgs is the request of [MethodDrawingAnnotationsAddFeatureControlFrame]: a
// GD&T feature control frame placed at (XMM, YMM) on the sheet. Characteristic is the geometric
// characteristic wire spelling (types.GeometricCharacteristic, e.g. "position"). Tolerance is the
// tolerance text (e.g. "0.5" or "⌀0.2"). Datums are the datum reference letters, in order (e.g.
// ["A","B","C"]). The frame, the characteristic symbol and the text are generated by the host.
type AddFeatureControlFrameArgs struct {
	Name           string   `json:"name,omitempty"`
	XMM            float64  `json:"xmm"`
	YMM            float64  `json:"ymm"`
	Characteristic string   `json:"characteristic"`
	Tolerance      string   `json:"tolerance"`
	Datums         []string `json:"datums,omitempty"`
}

// DeleteAnnotationArgs is the request of [MethodDrawingAnnotationsDelete].
type DeleteAnnotationArgs struct {
	Name string `json:"name"`
}

// AnnotationResult is the response of the add methods: the created annotation.
type AnnotationResult struct {
	Annotation DrawingAnnotationInfo `json:"annotation"`
}
