// SPDX-License-Identifier: Apache-2.0

package wire

// Drawing annotation wire DTOs (M14-F02 #813): the centre-of-gravity marker (a CoG indicator on
// a view, positioned from the referenced model's mass properties) and revision clouds (scalloped
// markup over a sheet region). Both are sheet-level annotations whose 2D geometry is generated by
// the host (/source, model/drawing).

// DrawingAnnotationInfo is the JSON shape of one drawing annotation.
type DrawingAnnotationInfo struct {
	Name       string `json:"name"`
	Kind       string `json:"kind"`               // types.DrawingAnnotationKind ("cog"/"revisionCloud"/"centerMark"/"centerline"/"featureControlFrame"/"datumFeature"/"surfaceTexture"/"partsList"/"balloon"/"holeTable")
	ViewName   string `json:"viewName,omitempty"` // the view a CoG marker / centre mark is on
	Tag        string `json:"tag,omitempty"`      // a revision cloud's label
	CurveCount int    `json:"curveCount"`
	RowCount   int    `json:"rowCount,omitempty"` // a parts list's data-row count (BOM items)
}

// ListDrawingAnnotationsResult is the response of [MethodDrawingAnnotationsList].
type ListDrawingAnnotationsResult struct {
	Annotations []DrawingAnnotationInfo `json:"annotations"`
}

// AddCoGMarkerArgs is the request of [MethodDrawingAnnotationsAddCoG]: a centre-of-gravity marker
// on ViewName, positioned at the referenced model's centre of mass projected into that view.
type AddCoGMarkerArgs struct {
	Name     string `json:"name,omitempty"`
	ViewName string `json:"viewName"`
}

// AddRevisionCloudArgs is the request of [MethodDrawingAnnotationsAddRevisionCloud]: a scalloped
// cloud over the sheet rectangle (XMM, YMM, WidthMM, HeightMM), with an optional revision Tag.
type AddRevisionCloudArgs struct {
	Name     string  `json:"name,omitempty"`
	XMM      float64 `json:"xmm"`
	YMM      float64 `json:"ymm"`
	WidthMM  float64 `json:"widthMm"`
	HeightMM float64 `json:"heightMm"`
	Tag      string  `json:"tag,omitempty"`
}

// AddCenterMarksArgs is the request of [MethodDrawingAnnotationsAddCenterMarks]: a centre mark
// (crosshair) at the centre of every circular model edge in ViewName. Each mark attaches to its
// edge, so it re-projects when the model changes. Coincident projections are marked once.
type AddCenterMarksArgs struct {
	ViewName string `json:"viewName"`
}

// CenterMarksResult is the response of [MethodDrawingAnnotationsAddCenterMarks]: the marks created.
type CenterMarksResult struct {
	Annotations []DrawingAnnotationInfo `json:"annotations"`
}

// AddCenterlinesArgs is the request of [MethodDrawingAnnotationsAddCenterlines]: the horizontal and
// vertical dash-dot symmetry centerlines through ViewName's centre, spanning its extent. The lines
// re-derive from the view's bounds, so they track the model.
type AddCenterlinesArgs struct {
	Name     string `json:"name,omitempty"`
	ViewName string `json:"viewName"`
}

// AddFeatureControlFrameArgs is the request of [MethodDrawingAnnotationsAddFeatureControlFrame]: a
// GD&T feature control frame placed at (XMM, YMM) on the sheet. Characteristic is the geometric
// characteristic wire spelling (types.GeometricCharacteristic, e.g. "position"). Tolerance is the
// tolerance text (e.g. "0.5" or "⌀0.2"). Datums are the datum reference letters, in order (e.g.
// ["A","B","C"]). The frame, the characteristic symbol and the text are generated by the host.
type AddFeatureControlFrameArgs struct {
	Name           string   `json:"name,omitempty"`
	XMM            float64  `json:"xmm"`
	YMM            float64  `json:"ymm"`
	Characteristic string   `json:"characteristic"`
	Tolerance      string   `json:"tolerance"`
	Datums         []string `json:"datums,omitempty"`
}

// AddDatumFeatureArgs is the request of [MethodDrawingAnnotationsAddDatumFeature]: a GD&T datum
// feature symbol at (XMM, YMM) on the sheet — the datum Letter (e.g. "A") in a box with a filled
// datum triangle. The symbol is generated by the host.
type AddDatumFeatureArgs struct {
	Name   string  `json:"name,omitempty"`
	XMM    float64 `json:"xmm"`
	YMM    float64 `json:"ymm"`
	Letter string  `json:"letter"`
}

// AddSurfaceTextureArgs is the request of [MethodDrawingAnnotationsAddSurfaceTexture]: an ISO 1302
// surface texture symbol at (XMM, YMM) on the sheet. Roughness is the finish value text (e.g.
// "1.6" or "Ra 3.2"). MaterialRemoval is the symbol variant (types.MaterialRemoval wire spelling:
// "any" basic, "required" machined, "prohibited" as-cast); empty means "any". The symbol and the
// roughness text are generated by the host.
type AddSurfaceTextureArgs struct {
	Name            string  `json:"name,omitempty"`
	XMM             float64 `json:"xmm"`
	YMM             float64 `json:"ymm"`
	Roughness       string  `json:"roughness,omitempty"`
	MaterialRemoval string  `json:"materialRemoval,omitempty"`
}

// AddPartsListArgs is the request of [MethodDrawingAnnotationsAddPartsList]: a parts list table at
// (XMM, YMM) on the sheet (its top-left corner), sourced from the referenced assembly's parts-only
// BOM (item number, part number, description, quantity). The table updates with the assembly.
type AddPartsListArgs struct {
	Name string  `json:"name,omitempty"`
	XMM  float64 `json:"xmm"`
	YMM  float64 `json:"ymm"`
}

// AddBalloonArgs is the request of [MethodDrawingAnnotationsAddBalloon]: a balloon (a circle
// holding the parts-list Item number) centred at (XMM, YMM) on the sheet. If LeaderXMM/LeaderYMM
// are given (non-zero), a leader is drawn from the balloon to that point — the component it tags.
type AddBalloonArgs struct {
	Name      string  `json:"name,omitempty"`
	XMM       float64 `json:"xmm"`
	YMM       float64 `json:"ymm"`
	Item      int     `json:"item"`
	LeaderXMM float64 `json:"leaderXmm,omitempty"`
	LeaderYMM float64 `json:"leaderYmm,omitempty"`
}

// AddHoleTableArgs is the request of [MethodDrawingAnnotationsAddHoleTable]: a hole table at (XMM,
// YMM) on the sheet (its top-left corner), listing every circular edge in the base view ViewName
// with its X/Y position from the view's datum origin and its diameter. The table updates with the
// model (rowCount in the result is the hole count).
type AddHoleTableArgs struct {
	Name     string  `json:"name,omitempty"`
	ViewName string  `json:"viewName"`
	XMM      float64 `json:"xmm"`
	YMM      float64 `json:"ymm"`
}

// RevisionTableRow is one row of a revision table: a revision identifier, its date, and a
// description of the change.
type RevisionTableRow struct {
	Revision    string `json:"revision"`
	Date        string `json:"date,omitempty"`
	Description string `json:"description,omitempty"`
}

// AddRevisionTableArgs is the request of [MethodDrawingAnnotationsAddRevisionTable]: a revision
// table at (XMM, YMM) on the sheet (its top-left corner), listing the given Rows (revision, date,
// description). The rows are user-supplied drawing history, persisted with the drawing.
type AddRevisionTableArgs struct {
	Name string             `json:"name,omitempty"`
	XMM  float64            `json:"xmm"`
	YMM  float64            `json:"ymm"`
	Rows []RevisionTableRow `json:"rows,omitempty"`
}

// AddRevisionTagArgs is the request of [MethodDrawingAnnotationsAddRevisionTag]: a revision tag (a
// triangle holding the Revision letter) centred at (XMM, YMM) on the sheet, flagging where that
// revision changed the drawing.
type AddRevisionTagArgs struct {
	Name     string  `json:"name,omitempty"`
	XMM      float64 `json:"xmm"`
	YMM      float64 `json:"ymm"`
	Revision string  `json:"revision"`
}

// DeleteAnnotationArgs is the request of [MethodDrawingAnnotationsDelete].
type DeleteAnnotationArgs struct {
	Name string `json:"name"`
}

// AnnotationResult is the response of the add methods: the created annotation.
type AnnotationResult struct {
	Annotation DrawingAnnotationInfo `json:"annotation"`
}
